### ISSUE TITLE
Â : The term 'Â' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by adriangrey** [markafox/GoDaddy_Powershell_DDNS#1]
After plugging in the variables, I am getting this error:

Â : The term 'Â' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At D:\Users\Adrian\Desktop\GoDaddy_Powershell_DDNS-master\godaddy_ddns.ps1:23 char:14
+ $currentIpÂ =Â Invoke-RestMethodÂ http://ipinfo.io/jsonÂ |Â SelectÂ - ...
+              ~
    + CategoryInfo          : ObjectNotFound: (Â:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Invoke-WebRequest : The remote server returned an error: (422) Unprocessable Entity.
At D:\Users\Adrian\Desktop\GoDaddy_Powershell_DDNS-master\godaddy_ddns.ps1:28 char:5
+     Invoke-WebRequest https://api.godaddy.com/v1/domains/$domain/reco ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

I'm probably just stupid, and have no idea what I'm doing lol

**Comment by markafox** [comment]
It is an encoding issue.  If you are just cutting and pasting the code, make sure you select "RAW" at the top left of the code window first.  There should not be any  'Â'  in the script.  In your editor, the script should look just like it does when displayed in raw on GitHub.
